In [4]:
import numpy as np
from PIL import Image

In [32]:
def end_point_error(pred_img, ground_truth):
    gray_pred_img = Image.open(pred_img).convert('L')
    pred = np.array(gray_pred_img)
    gray_ground_truth = Image.open(ground_truth).convert('L')
    gt = np.array(gray_ground_truth)
    epe = np.mean(abs(pred-gt))
    return epe

In [40]:
def error_rate(pred_img, ground_truth, threshold=3):
    gray_pred_img = Image.open(pred_img).convert('L')
    pred = np.array(gray_pred_img)
    gray_ground_truth = Image.open(ground_truth).convert('L')
    gt = np.array(gray_ground_truth)
    disparity = abs(pred-gt)>3
    print(np.mean(disparity))
    er = 100*np.mean(disparity)
    return er

In [41]:
end_point_error('input_images/part2/1/0015_rgb_left.png', 'input_images/part2/1/0015_gt.png')

[[ 42  40  37 ...  50  54  75]
 [ 40  39  39 ...  52  45  48]
 [ 42  39  39 ...  48  46  47]
 ...
 [  3  50  84 ... 237 227 238]
 [ 67  87  94 ...   1 242 247]
 [ 96  96  94 ...   5   0   5]]


94.82135223765432

In [42]:
error_rate('input_images/part2/1/0015_rgb_left.png', 'input_images/part2/1/0015_gt.png')

0.9918441358024691


99.18441358024691